apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
      - name: comment-service
        image: localhost:5000/comment-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: NODE_ENV
          value: "production"
        - name: COMMENT_SERVICE_PORT   # <-- Add this
          value: "3004"            # <-- Add this
---
apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  selector:
    app: comment-service
  ports:
  - port: 3004
    targetPort: 3004
  type: NodePort
