apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - name: post-service
        image: localhost:5000/post-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        - name: POST_SERVICE_PORT   
          value: "3002"            
---
apiVersion: v1
kind: Service
metadata:
  name: post-service-svc
spec:
  selector:
    app: post-service
  ports:
  - port: 3002
    targetPort: 3002
  type: NodePort
